# -*- coding: utf-8 -*-
"""Additional pool questions - Manager and Sr. Manager."""
from testbank import mcq, num, wr, FUND, MET, DIAG

# ============================================== MANAGER (+10 FUND, +13 MET, +11 DIAG)
MGR_EXTRA = [
mcq("M27", FUND, "You want Smart Bidding to optimise towards qualified leads rather than form fills. You need:",
    ["A higher tCPA target",
     "Qualified-lead outcomes fed back to Google with values, via offline conversion import",
     "To switch to Maximise Clicks",
     "To exclude unqualified search terms"], 1,
    "Smart Bidding optimises to what you send it. Negatives help, but only feedback changes what it chases."),
mcq("M28", FUND, "In a Shopping campaign, what actually determines which searches your product shows for?",
    ["The keywords in the ad group",
     "The product feed data, primarily the title, attributes and category",
     "The campaign priority setting",
     "The landing page content"], 1,
    "The feed is the targeting mechanism. This is why title optimisation is the highest-leverage Shopping lever."),
mcq("M29", FUND, "Campaign priority settings in Shopping are used to:",
    ["Decide which campaign gets budget first",
     "Control which campaign serves when the same product is eligible in more than one",
     "Set the order products appear in",
     "Prioritise high-margin products automatically"], 1,
    "Combined with shared negatives, priority is how you tier traffic by query intent."),
mcq("M30", FUND, "A supplemental feed lets you:",
    ["Add a second set of products",
     "Override or add attributes without editing the primary feed source",
     "Feed data to Meta as well as Google",
     "Bypass Merchant Center review"], 1,
    "Which is what makes title testing possible without asking the client's dev team for every change."),
mcq("M31", FUND, "In PMax, 'audience signals' are:",
    ["Hard targeting - the campaign only reaches those people",
     "A starting hint to speed up learning; the campaign can still go beyond them",
     "Only used for the Display network portion",
     "Automatically generated and cannot be edited"], 1,
    "A signal, not a constraint. Treating them as targeting is a very common misunderstanding."),
mcq("M32", FUND, "Value rules in Google Ads let you:",
    ["Set different bids by device",
     "Adjust conversion value by location, device or audience so bidding reflects real worth",
     "Set a minimum order value",
     "Exclude low-value products from Shopping"], 1,
    "The practical route to margin-aware or new-customer-aware bidding without rebuilding the feed."),
mcq("M33", FUND, "Meta's existing-customer budget cap in Advantage+ Shopping exists to:",
    ["Reduce total spend",
     "Limit how much of the budget goes to people who have already bought",
     "Cap the frequency of ads to customers",
     "Prevent the campaign exiting the learning phase"], 1,
    "It is the main lever for pushing ASC towards new-customer acquisition rather than harvesting."),
mcq("M34", FUND, "You want to test whether Audience Network placements are genuinely low quality. You should:",
    ["Exclude it and compare overall CPA before and after",
     "Look at the placement breakdown for delivery, CPA and downstream quality before excluding anything",
     "Ask Meta support",
     "Exclude it permanently - it is well known to be poor"], 1,
    "Check the breakdown first. Reflexive exclusion on reputation costs cheap inventory for no evidenced reason."),
mcq("M35", FUND, "Which is the strongest reason to keep brand search in its own campaign?",
    ["Brand keywords have higher Quality Scores",
     "So brand performance does not flatter or distort non-brand reporting and budgeting",
     "Google requires it",
     "Brand campaigns need different ad copy"], 1,
    "Reporting integrity and budget control. Blending brand into generic is how accounts look better than they are."),
mcq("M36", FUND, "An account has data-driven attribution and a 30-day conversion window. A client asks why "
    "last week's ROAS keeps changing. The answer is:",
    ["The platform is unreliable",
     "Conversions are credited back to the click date, so recent days fill in over time",
     "Someone is editing the campaigns",
     "The currency conversion updates daily"], 1,
    "Back-filling is expected. Agreeing a reporting lag convention up front prevents this conversation entirely."),
num("M37", MET, "AOV 3,200. COGS 1,400. Shipping and fees 400. What is the contribution margin, as a percentage?", 43.75,
    "(3,200 - 1,800) / 3,200 = 43.75%."),
num("M38", MET, "Contribution margin is 25%. What is the break-even ROAS?", 4,
    "1 / 0.25 = 4."),
num("M39", MET, "Total revenue 12,000,000. Total ad spend 3,000,000. What is the MER?", 4,
    "12,000,000 / 3,000,000 = 4."),
num("M40", MET, "A client needs 60 sales a month. Lead-to-sale is 15%. How many leads per month?", 400,
    "60 / 0.15 = 400."),
num("M41", MET, "Budget 900,000 and you need 400 leads. What CPL do you need?", 2250,
    "900,000 / 400 = 2,250."),
num("M42", MET, "Spend rose from 500,000 to 700,000; conversions rose from 250 to 310. "
    "What is the marginal CPA on the extra spend?", 3333.33,
    "200,000 / 60 = 3,333. Against a blended CPA of 2,258, the incremental spend is far more expensive.", 0.01),
num("M43", MET, "Revenue 5,000,000 at a 40% contribution margin. Ad spend 1,600,000. What is the contribution "
    "after ad spend?", 400000,
    "5,000,000 x 0.40 = 2,000,000, minus 1,600,000 = 400,000."),
num("M44", MET, "Customer LTV is 9,000 with a 45% margin. What is the maximum CAC to break even on lifetime value?", 4050,
    "9,000 x 0.45 = 4,050."),
mcq("M45", MET, "Blended ROAS is flat but new-customer CAC has risen 40%. What is most likely happening?",
    ["Nothing - blended ROAS is the metric that matters",
     "Spend has shifted towards retargeting and existing customers, propping up the blended number",
     "The tracking is broken",
     "Competitors have entered the market"], 1,
    "The classic silent failure: the account looks stable while the acquisition engine stalls."),
mcq("M46", MET, "You have 40 conversions on variant A and 33 on variant B after two weeks. You should:",
    ["Roll out A",
     "Recognise this is within noise and either run longer or accept no difference was found",
     "Roll out B because it had a better CTR",
     "Split budget 70/30 towards A"], 1,
    "At these volumes the difference is not distinguishable from chance. Declaring a winner here is how false learnings spread."),
mcq("M47", MET, "The most defensible way to set next quarter's target is:",
    ["Add 20% to last quarter",
     "Model from marginal returns and headroom, present a range, and state the assumptions",
     "Use the client's board target",
     "Match the category benchmark"], 1,
    "A range with assumptions is honest and defensible. A single number is a hostage."),
mcq("M48", MET, "Which is the best evidence that a landing page change worked?",
    ["Conversion rate went up the following week",
     "A controlled split test with adequate conversion volume showed a lift",
     "The client prefers the new page",
     "Bounce rate fell"], 1,
    "Week-on-week movement confounds with traffic mix, seasonality and everything else that changed."),
mcq("M49", MET, "You are asked for one metric to judge an ecommerce account's health. You pick:",
    ["Platform ROAS", "MER, alongside new-customer share",
     "Total conversions", "Average CPC"], 1,
    "MER reflects the P&L. New-customer share tells you whether the growth engine is actually running."),
mcq("M50", DIAG, "Lead volume is stable but sales say close rates halved. Nothing changed in the account. First move:",
    ["Increase lead volume to compensate",
     "Get the actual lead records and review them with sales to find what changed in the mix",
     "Lower CPL targets",
     "Assume it is a sales-side problem"], 1,
    "Look at the leads themselves. The mix has almost certainly shifted even if the account settings have not."),
mcq("M51", DIAG, "A PMax campaign launched three weeks ago and CPA looks excellent. Before celebrating, check:",
    ["Whether it has exited the learning period",
     "Whether it is cannibalising brand and existing search conversions",
     "Whether the asset group has enough creative",
     "Whether the budget is fully spending"], 1,
    "PMax's early wins are frequently conversions your search campaigns were already getting."),
mcq("M52", DIAG, "The client's developer changed the site last night. The safest immediate action is:",
    ["Pause all campaigns until it is verified",
     "Verify tracking is still firing and check the key user journeys, then decide",
     "Do nothing - site changes rarely affect ads",
     "Increase bids to offset any drop"], 1,
    "Verify, then decide. Pausing everything is over-reaction; ignoring it is how a week of spend is wasted."),
mcq("M53", DIAG, "You disagree with the client's in-house team on strategy, and they outrank you in the room. You:",
    ["Defer entirely",
     "Understand their reasoning, state your position with evidence and a cost estimate, propose a test, document the outcome",
     "Escalate to their manager",
     "Agree publicly and do it your way"], 1,
    "They may have context you lack - stock, margin, a board commitment. Propose a test rather than win an argument."),
mcq("M54", DIAG, "Two clients escalate on the same morning and you have a pitch at 3pm. You:",
    ["Handle whoever is angriest first",
     "Triage by impact and reversibility, send holding responses with a specific time, protect the pitch prep",
     "Work through them in the order they arrived",
     "Delegate both to your associate"], 1,
    "Triage by consequence, not volume. A holding response with a time commitment costs 30 seconds and buys hours."),
mcq("M55", DIAG, "Your associate keeps missing QA checks. The most useful first step is:",
    ["Formal warning",
     "Work out whether it is capability, capacity or carelessness - the fix differs for each",
     "Do the QA yourself from now on",
     "Reduce their workload"], 1,
    "Diagnose before intervening. Doing it yourself removes the symptom and guarantees the recurrence."),
mcq("M56", DIAG, "A client is going quiet - slower replies, fewer meetings, no new briefs. You:",
    ["Wait for them to raise anything that is wrong",
     "Proactively ask for a conversation about how the relationship is going",
     "Send more detailed reports",
     "Offer a discount"], 1,
    "Silence is the most reliable churn signal there is. Waiting to be told is how accounts are lost without warning."),
mcq("M57", DIAG, "You are two weeks from leave and have four accounts. A clean handover means:",
    ["Telling the team you will check email",
     "A written account state, live tests with end dates, a named owner per account and a live briefing",
     "Setting an out-of-office with an escalation address",
     "Pausing all tests until you return"], 1,
    "A named owner per account, not a group inbox. And a live briefing - documents alone do not transfer context."),
mcq("M58", DIAG, "The client asks you to compare this month against a month you know was unusually weak. You:",
    ["Use it - they asked for it",
     "Provide it, and also show a fair comparison so the picture is not misleading",
     "Refuse to provide the comparison",
     "Provide it without comment"], 1,
    "Answer the question AND give the honest context. Silently allowing a flattering comparison is a slow-burning problem."),
mcq("M59", DIAG, "Your account's performance is fine, but the client's business is struggling for reasons outside media. You:",
    ["Keep reporting on media metrics - that is your scope",
     "Raise it directly, connect your work to their actual problem, and adjust what you optimise for",
     "Reduce spend without telling them",
     "Wait for them to bring it up"], 1,
    "The account being fine is not the same as the client being fine. Managers who notice the difference keep clients."),
]

MGR_WRITTEN_EXTRA = [
wr("MW4", "A client's lead volume is at target and CPL is at target, but their sales team says close rates have "
   "halved since last quarter. Walk us through how you would investigate, and what you would do.", 250,
   "Should get to traffic mix, not bid levels: what changed in source, match type, campaign type (PMax launch?), "
   "geography, or the offer. Bonus for checking client-side changes - sales headcount, follow-up speed, pricing. "
   "Score 0-1 for treating it purely as the sales team's problem."),
wr("MW5", "Describe how you would take over a client account that is unhappy with the previous agency. "
   "What do you do in the first 30 days, and what do you deliberately avoid?", 250,
   "Look for: audit before action, early expectation reset, a quick visible win balanced against not over-promising, "
   "and a refusal to trash the previous agency. The 'deliberately avoid' half is the more revealing one."),
wr("MW6", "What is something widely believed in performance marketing that you think is wrong? Make the case, "
   "and then give the strongest argument against your own position.", 200,
   "Tests independent thinking AND intellectual honesty. The counter-argument half is what separates a considered "
   "position from a contrarian pose. Score 0-1 for no position, or a position with no counter-argument."),
]

# ============================================ SR. MANAGER (+15 MET, +15 DIAG)
SR_EXTRA = [
num("S25", MET, "Contribution margin is 55%. What is the break-even ROAS? (two decimal places)", 1.82,
    "1 / 0.55 = 1.818, so 1.82.", 0.02),
num("S26", MET, "Spend goes from 4,000,000 to 5,000,000. Revenue goes from 14,000,000 to 16,500,000. "
    "What is the marginal ROAS?", 2.5,
    "2,500,000 / 1,000,000 = 2.5."),
num("S27", MET, "A client's blended CAC is 3,000 with a 12-month LTV of 11,000 at 40% margin. "
    "What is the LTV:CAC ratio on a margin basis?", 1.47,
    "11,000 x 0.40 = 4,400. 4,400 / 3,000 = 1.47 - considerably weaker than the 3.7 the revenue figure suggests.", 0.02),
num("S28", MET, "Portfolio fee revenue is 4,000,000 a month at an average 45% servicing cost. "
    "What is monthly gross profit?", 2200000,
    "4,000,000 x 0.55 = 2,200,000."),
num("S29", MET, "You must cut servicing hours 20% across a team costing 1,500,000 a month. "
    "What is the monthly saving if cost scales with hours?", 300000,
    "1,500,000 x 0.20 = 300,000."),
num("S30", MET, "New customers are 30% of 2,000 monthly orders. Total ad spend is 1,800,000. "
    "What is the new-customer CAC?", 3000,
    "600 new customers. 1,800,000 / 600 = 3,000. The blended figure of 900 would badly mislead."),
num("S31", MET, "Target payback is 6 months and monthly contribution per customer is 500. What is the maximum CAC?", 3000,
    "6 x 500 = 3,000."),
num("S32", MET, "Account A: 3,000,000 spend at 3.0 ROAS. Account B: 1,000,000 spend at 6.0 ROAS. "
    "What is the combined ROAS?", 3.75,
    "(9,000,000 + 6,000,000) / 4,000,000 = 3.75. Note it is spend-weighted, not the 4.5 average of the two."),
mcq("S33", MET, "A client's revenue is up 15% and ad spend is up 15%. Their finance director says profit fell. "
    "The most likely reason is:",
    ["The platforms are misreporting",
     "Discounting, returns or product mix eroded contribution margin",
     "The ad spend was recorded twice",
     "Revenue growth always lags spend"], 1,
    "Revenue growth at constant ROAS can still destroy profit if margin moved. Senior people ask about margin unprompted."),
mcq("S34", MET, "The main limitation of marketing mix modelling for a mid-sized account is:",
    ["It only works for TV advertising",
     "It needs a long history and substantial spend variation to produce reliable coefficients",
     "It cannot include digital channels",
     "It requires user-level data"], 1,
    "Below a certain spend and history, MMM produces confident-looking output with very wide real error bars."),
mcq("S35", MET, "You want to prove brand search is incremental. The cleanest test is:",
    ["Compare brand ROAS to non-brand ROAS",
     "A geo-split holdout where brand campaigns are paused in matched regions",
     "Pause brand for a week and compare to the week before",
     "Compare branded organic traffic to branded paid traffic"], 1,
    "A matched geo holdout controls for time-based confounders. A before/after week does not."),
mcq("S36", MET, "In a geo holdout test, the most common design mistake is:",
    ["Running it for too long",
     "Test and control regions that are not comparable in baseline, seasonality or channel mix",
     "Including too many regions",
     "Measuring backend revenue rather than platform conversions"], 1,
    "Matching is everything. Badly matched geos produce a confident number that means nothing."),
mcq("S37", MET, "A forecast you present should always include:",
    ["A single committed number the client can plan against",
     "A range, the assumptions behind it, and what would invalidate it",
     "The best case, to secure budget approval",
     "Last year's actuals only"], 1,
    "Ranges with assumptions survive contact with reality. Point forecasts become the number you are judged against."),
mcq("S38", MET, "Which portfolio-level metric best predicts revenue risk over the next two quarters?",
    ["Average ROAS across accounts",
     "Client concentration and account tenure alongside satisfaction signals",
     "Total spend under management",
     "Number of active campaigns"], 1,
    "Concentration is the risk that actually kills agencies. Performance metrics are lagging indicators of it."),
mcq("S39", MET, "Two accounts have identical ROAS. Account A is 60% retargeting, Account B is 15%. You conclude:",
    ["They are performing equally well",
     "Account B is very likely producing more incremental revenue",
     "Account A is better optimised",
     "You need creative data before saying anything"], 1,
    "Identical reported ROAS with very different incrementality. This is why channel mix belongs in every review."),
mcq("S40", DIAG, "You inherit a portfolio and one account is losing money on servicing but is the founder's "
    "personal relationship. You:",
    ["Leave it alone",
     "Quantify the loss, present it with options, and let the commercial owner decide with real numbers",
     "Reduce the service level quietly",
     "Recommend resigning the account"], 1,
    "Your job is to make the trade-off visible with numbers, not to make the relationship decision unilaterally."),
mcq("S41", DIAG, "Your strongest manager tells you they have been approached by a competitor. You:",
    ["Immediately counter-offer",
     "Find out what is actually driving it before discussing money",
     "Escalate to HR and start recruiting a replacement",
     "Tell them to let you know what they decide"], 1,
    "Money is rarely the real reason and a counter-offer that fixes nothing buys about four months."),
mcq("S42", DIAG, "A client demands you remove a team member from their account for reasons you think are unfair. You:",
    ["Comply immediately",
     "Understand the specific incidents, protect the team member's account of it, then decide - and tell them honestly either way",
     "Refuse and defend the team member",
     "Move the person and tell them it was their performance"], 1,
    "Get the facts, and never let someone believe a client complaint was a performance judgment when it was not."),
mcq("S43", DIAG, "Your team is at capacity and sales wants to sign two more accounts. You:",
    ["Say no until you can hire",
     "Model the capacity honestly, show what would have to give, and put the decision in front of the commercial owner",
     "Accept and work out the details later",
     "Accept but reduce service on existing accounts"], 1,
    "Make the trade-off explicit. Quietly absorbing it is how service quality decays without anyone deciding to let it."),
mcq("S44", DIAG, "The single most useful thing to do in the first two weeks of owning a new portfolio is:",
    ["Rebuild the weakest account",
     "Talk to every client and every team member, and read the last two quarters of reporting",
     "Introduce a new reporting template",
     "Meet the biggest client"], 1,
    "Diagnosis, breadth first. Acting on the first account you look at is how you solve the wrong problem well."),
mcq("S45", DIAG, "A pitch prospect asks for a guaranteed CPA before you have seen their data. You:",
    ["Give a conservative number to stay in the running",
     "Explain what you would need to see, give a directional range with conditions, and be clear about what you will not guarantee",
     "Refuse to discuss numbers",
     "Guarantee it and manage expectations after winning"], 1,
    "A guarantee made without data is a client conflict scheduled for month three."),
mcq("S46", DIAG, "You discover a team member has been reporting a metric misleadingly for a quarter. You:",
    ["Correct it quietly going forward",
     "Establish whether it was error or intent, correct it with the client yourself, and address the behaviour",
     "Report it to the client as the team member's error",
     "Address it internally without telling the client"], 1,
    "Correct it with the client yourself - the accountability is yours. Error and intent need very different responses."),
mcq("S47", DIAG, "Two of your managers are in open conflict about account ownership. You:",
    ["Split the accounts down the middle",
     "Get both accounts of it separately, decide, explain the reasoning to both, and make the decision stick",
     "Let them work it out between themselves",
     "Reassign both to yourself"], 1,
    "Decide and explain. Unresolved ownership conflicts spread faster than almost anything else on a team."),
mcq("S48", DIAG, "The best way to know whether your process changes actually worked is:",
    ["Ask the team if they like them",
     "Check whether they are still being followed six months later without enforcement",
     "Count how many people were trained",
     "Measure time saved in the first month"], 1,
    "Survival without enforcement. Everything else measures compliance, not adoption."),
mcq("S49", DIAG, "You have to let someone go for performance. Before that conversation you should have:",
    ["Documented performance issues, given clear expectations and a real chance to improve",
     "Found their replacement",
     "Told the rest of the team",
     "Reduced their account load quietly"], 0,
    "If the conversation is a surprise, the failure was managerial. Clarity earlier is the kind version."),
mcq("S50", DIAG, "A client wants to move to a performance-based fee tied to ROAS. Your first concern is:",
    ["Whether the team can hit the number",
     "Whether you control the variables it depends on - site, pricing, stock, product",
     "Whether the fee would be higher or lower",
     "Whether competitors offer the same"], 1,
    "Being paid on an outcome you only partly control is how agencies lose money on their best work."),
mcq("S51", DIAG, "The most reliable early warning that an account is about to churn is:",
    ["A drop in ROAS",
     "A change in engagement - slower replies, cancelled meetings, a new stakeholder appearing",
     "A request for a fee reduction",
     "A competitor pitch"], 1,
    "By the time they mention fees or competitors the decision is usually made. Engagement moves first."),
mcq("S52", DIAG, "Your team keeps escalating decisions to you that they could make themselves. This means:",
    ["They lack confidence and need more experience",
     "The decision rights and the tolerance for mistakes have not been made explicit",
     "You hired the wrong people",
     "The accounts are too complex"], 1,
    "People escalate when the cost of being wrong is unclear. Name the decision rights and the acceptable error."),
mcq("S53", DIAG, "You are asked to present quarterly results that are materially worse than forecast. You:",
    ["Lead with the wins and cover the shortfall briefly",
     "Lead with the shortfall, explain the cause honestly including your own part, and bring a revised plan",
     "Delay the review until performance recovers",
     "Attribute it to market conditions"], 1,
    "Lead with the bad news. Burying it is what turns a bad quarter into a lost account."),
mcq("S54", DIAG, "An intern on your team makes a costly mistake in their first month. The most important thing you do is:",
    ["Make sure they understand the seriousness",
     "Fix it, then examine what in your process allowed a first-month intern to make it",
     "Reduce their access permanently",
     "Escalate it so it is on record"], 1,
    "A junior person who could cause that damage unsupervised is a process failure, not a personnel one."),
]

SR_WRITTEN_EXTRA = [
wr("SW4", "You are asked to build the case for adding a fifth person to your team. Write the argument you would "
   "put to the person who controls the budget.", 300,
   "Should be commercial, not operational: revenue at risk, capacity maths, what breaks without it, what the "
   "alternative is (process, tooling, scope change), and when it pays back. Score 0-1 for 'the team is stretched'."),
wr("SW5", "Describe the hardest conversation you have had with a client. What did you say, and what would you "
   "say differently now?", 250,
   "Look for a real conversation with words they actually used, not a summary. The 'differently now' half tests "
   "whether they have reflected or just survived it."),
wr("SW6", "How would you decide whether an account is worth keeping? Give the criteria and how you would weigh them.", 250,
   "Strong answers combine commercials (fee, servicing cost, margin, payment behaviour), strategic value (reference, "
   "category, learning) and human cost (team morale, unreasonable stakeholders). Weak answers consider fee only."),
]
