# -*- coding: utf-8 -*-
"""Additional pool questions - Intern and Associate."""
from testbank import mcq, num, wr, FUND, MET, DIAG

# ============================================== INTERN  (+10 FUND, +10 MET, +7 DIAG)
INTERN_EXTRA = [
mcq("I19", FUND, "Which of these is NOT something you set at the campaign level in Google Ads?",
    ["Daily budget", "Target locations", "The ad headline", "Bid strategy"], 2,
    "Headlines live on the ad. Everything else is campaign-level."),
mcq("I20", FUND, "What is a conversion in Google Ads?",
    ["Any click on your ad",
     "An action you have defined as valuable and told Google to track",
     "A sale, and only a sale",
     "A visit to your website"], 1,
    "You define it. It might be a purchase, a form fill, a call or a booking - which is why definitions must be agreed with the client."),
mcq("I21", FUND, "Phrase match will show your ad when the search term:",
    ["Contains the meaning of your keyword",
     "Contains your keyword's exact words in any order",
     "Is completely unrelated but popular",
     "Is longer than five words"], 0,
    "Phrase match covers searches that include the meaning of your keyword."),
mcq("I22", FUND, "On Meta, what is a 'placement'?",
    ["The position of your ad in the auction",
     "The specific surface an ad appears on, such as Instagram Reels or Facebook Feed",
     "The country you are targeting",
     "The order in which your ads run"], 1,
    "Feed, Reels, Stories, Marketplace, Audience Network and so on."),
mcq("I23", FUND, "What is remarketing (or retargeting)?",
    ["Running the same ad twice",
     "Showing ads to people who have already interacted with your brand",
     "Rewriting an ad that performed badly",
     "Bidding on a competitor's brand name"], 1,
    "Warm audiences. Cheap conversions, but usually the least incremental spend in the account."),
mcq("I24", FUND, "A landing page is:",
    ["The homepage of the website",
     "The page a user arrives on after clicking your ad",
     "The final page of a checkout process",
     "The page where you edit your ads"], 1,
    "It is part of the ad experience, and often where a campaign is actually failing."),
mcq("I25", FUND, "Why do advertisers bid on their own brand name?",
    ["Because it is required by Google",
     "To defend against competitors bidding on it and to control the message",
     "Because it is the only way to appear in search results",
     "To improve their organic ranking"], 1,
    "Cheap and defensive - but it takes credit for demand that already existed, so report it separately."),
mcq("I26", FUND, "In Google Ads, an 'impression' means:",
    ["Someone clicked your ad",
     "Your ad was shown",
     "Someone converted",
     "Your ad was approved"], 1,
    "Shown, not clicked. The distinction underpins CTR and CPM."),
mcq("I27", FUND, "What is A/B testing?",
    ["Running ads on two platforms at once",
     "Comparing two versions that differ by one variable, to see which performs better",
     "Testing an ad before it goes live",
     "Running the same ad to two different countries"], 1,
    "One variable. Changing two things at once tells you nothing about which one worked."),
mcq("I28", FUND, "Which of these would you expect to have the HIGHEST purchase intent?",
    ["Someone watching a YouTube video about running",
     "Someone scrolling Instagram who sees a shoe ad",
     "Someone searching 'buy nike pegasus 41 size 9'",
     "Someone who visited a shoe blog last month"], 2,
    "Intent is the core concept behind why search and social behave so differently."),
num("I29", MET, "Impressions 50,000. Clicks 1,500. What is the CTR, as a percentage?", 3,
    "1,500 / 50,000 = 3%."),
num("I30", MET, "Spend 18,000. Conversions 12. What is the CPA?", 1500,
    "18,000 / 12 = 1,500."),
num("I31", MET, "Revenue 240,000. Spend 60,000. What is the ROAS?", 4,
    "240,000 / 60,000 = 4."),
num("I32", MET, "You spent 12,000 and got 300 clicks. What is the CPC?", 40,
    "12,000 / 300 = 40."),
num("I33", MET, "800 clicks and a 5% conversion rate. How many conversions?", 40,
    "800 x 0.05 = 40."),
num("I34", MET, "A product sells for 2,000 and you sold 45 units. What is the revenue?", 90000,
    "2,000 x 45 = 90,000."),
num("I35", MET, "CPC is 25 and you have a budget of 20,000. How many clicks can you expect?", 800,
    "20,000 / 25 = 800."),
num("I36", MET, "Last month CPA was 1,000. This month it is 1,250. What is the percentage increase?", 25,
    "(1,250 - 1,000) / 1,000 = 25%."),
mcq("I37", MET, "A campaign has a 12% CTR and another has 1.2%. What is the most likely explanation?",
    ["The first campaign has a much bigger budget",
     "The first is probably brand or high-intent search; the second is probably cold prospecting",
     "The second campaign is broken",
     "The first campaign has better images"], 1,
    "CTR is driven by intent and match between query and ad, not by quality in the abstract."),
mcq("I38", MET, "Which pair of metrics tells you the MOST about whether a campaign is working?",
    ["Impressions and reach",
     "CPA and conversion volume, against a target",
     "CTR and CPC",
     "Frequency and CPM"], 1,
    "Everything else is a diagnostic. Only cost per outcome and volume answer 'is this working'."),
mcq("I39", DIAG, "Your CTR is high but you have no conversions at all. Where do you look first?",
    ["Increase the budget",
     "The landing page and whether conversion tracking is working",
     "Add more keywords",
     "Change the bidding strategy"], 1,
    "People are clicking, so the ad works. The failure is after the click - page, offer, or measurement."),
mcq("I40", DIAG, "You are asked to pull a report and you notice a number that looks wrong. You:",
    ["Send it anyway - it was not your job to check",
     "Fix it yourself without telling anyone",
     "Flag it, say what looks wrong and why, and ask before sending",
     "Remove that section quietly"], 2,
    "Noticing is good. Flagging it rather than hiding or ignoring it is the behaviour that matters."),
mcq("I41", DIAG, "You have been asked to learn a platform you have never used, starting Monday. What do you do first?",
    ["Wait for formal training",
     "Read the official documentation and look at an existing account",
     "Watch as many YouTube videos as possible",
     "Ask a colleague to do the work for you"], 1,
    "Official docs plus the real account beats scattered video. Look for a sequenced plan, not enthusiasm."),
mcq("I42", DIAG, "You finish your work at 5pm and nothing is urgent. The best use of the next hour is:",
    ["Ask your manager if anyone needs help, or work on learning something relevant",
     "Look busy until everyone else leaves",
     "Start a large new project without telling anyone",
     "Leave immediately without saying anything"], 0,
    "Offering help or self-directed learning. Performing busyness and disappearing silently are both weak signals."),
mcq("I43", DIAG, "A colleague points out a mistake in your work in front of the team. You:",
    ["Explain why it was not really your fault",
     "Thank them, fix it, and check whether it happened anywhere else",
     "Say nothing and fix it later",
     "Ask them to raise things privately next time, and leave it there"], 1,
    "Fixing it AND checking for the same error elsewhere is what separates accountability from compliance."),
mcq("I44", DIAG, "You do not understand something in a client call and everyone else seems to. You:",
    ["Nod along and look it up afterwards",
     "Ask the question, or note it and ask your manager immediately after",
     "Ignore it - it is probably not important",
     "Ask a colleague to explain during the call over chat"], 1,
    "Either is fine. Nodding along and hoping is how misunderstandings become client problems."),
mcq("I45", DIAG, "Two tasks are both due today and you cannot finish both. You:",
    ["Do the easier one so at least one is finished",
     "Tell your manager early, with a recommendation on which should slip and why",
     "Work late and do both badly",
     "Do half of each"], 1,
    "Early communication plus a recommendation. Look for the recommendation - anyone can raise a problem."),
]

INTERN_WRITTEN_EXTRA = [
wr("IW3", "Describe a time you had to figure something out with no one to ask. What was it, what did you try, "
   "and how did it turn out?", 150,
   "Resourcefulness and sequence. Look for what they actually tried, in order, and whether they knew when to stop. "
   "A failed attempt described honestly scores higher than a vague success."),
wr("IW4", "Look at any brand's Instagram or Google ads that you have seen recently. What do you think they are trying "
   "to achieve, who is it aimed at, and what would you change?", 150,
   "Tests whether they observe advertising critically at all. Strong answers infer the objective from the ad's "
   "construction. Weak answers comment on whether they personally liked it."),
]

# ============================================ ASSOCIATE (+10 FUND, +12 MET, +8 DIAG)
ASSOC_EXTRA = [
mcq("A25", FUND, "Which negative keyword match type would stop your ad for the search 'free crm software'?",
    ["Negative broad 'free'", "Negative exact 'free'",
     "Negative phrase 'software free'", "None of these"], 0,
    "Negative broad on 'free' blocks any search containing that word. Negative exact only blocks the term 'free' alone."),
mcq("A26", FUND, "Auction Insights tells you:",
    ["What your competitors are bidding",
     "Which domains you compete with, and their impression share, overlap rate and outranking share",
     "Your competitors' conversion rates",
     "The exact position your ad appeared in"], 1,
    "Never their bids or their results - only relative auction presence."),
mcq("A27", FUND, "A 'close variant' means Google may show your ad for a search that:",
    ["Is in a different language",
     "Has the same meaning as your keyword, including misspellings and plurals",
     "Contains any word from your keyword",
     "Is in a different country"], 1,
    "Which is why exact match is not literal and why the search terms report still matters."),
mcq("A28", FUND, "In Meta, what does 'frequency' measure?",
    ["How often you refresh your creative",
     "Average number of times each person saw your ad",
     "How many ads are running in an ad set",
     "How often the algorithm updates delivery"], 1,
    "Impressions / reach. Rising frequency with falling CTR is the classic fatigue signature."),
mcq("A29", FUND, "Which Meta objective would you use to drive purchases on a website?",
    ["Traffic", "Engagement", "Sales", "Awareness"], 2,
    "Sales, optimising for the purchase event. Traffic buys cheap clicks from people who do not buy."),
mcq("A30", FUND, "What is a customer match (or customer list) audience?",
    ["An audience Google builds from similar advertisers",
     "An audience built by uploading your own hashed customer data",
     "Anyone who has visited your website",
     "People who match your ideal customer profile demographically"], 1,
    "Your first-party data, hashed before upload. Increasingly the most valuable targeting asset you have."),
mcq("A31", FUND, "You want to stop showing ads to existing customers on a prospecting campaign. You would:",
    ["Lower the bid on that audience",
     "Exclude a customer list or purchaser audience at the campaign or ad set level",
     "Add negative keywords",
     "Reduce the daily budget"], 1,
    "Exclusion, not bid adjustment. Prospecting budget spent on existing customers is not prospecting."),
mcq("A32", FUND, "In Google Ads, what does a 'Limited by budget' status mean?",
    ["The campaign has spent its lifetime budget",
     "The campaign could get more impressions if the budget were higher",
     "The account payment method has failed",
     "The bid strategy has been paused"], 1,
    "It is an opportunity flag, not an error - but only worth acting on if the campaign is hitting its efficiency target."),
mcq("A33", FUND, "Which is the best reason to split a campaign in two?",
    ["The keywords are different",
     "The two groups have different economics or different CPA targets",
     "The campaign has too many keywords",
     "To make reporting look neater"], 1,
    "Segment on economics, not on tidiness. Splitting dilutes conversion data the algorithm needs."),
mcq("A34", FUND, "Dynamic product ads on Meta require, at minimum:",
    ["A video creative for each product",
     "A synced catalog and pixel/CAPI events passing matching content IDs",
     "A minimum of 1,000 products",
     "A separate Business Manager"], 1,
    "The content_id link between catalog and pixel is what makes them dynamic. It is also what most often breaks."),
num("A35", MET, "Spend 180,000. Revenue 630,000. What is the ROAS?", 3.5,
    "630,000 / 180,000 = 3.5."),
num("A36", MET, "You need 250 conversions and your CVR is 4%. How many clicks do you need?", 6250,
    "250 / 0.04 = 6,250."),
num("A37", MET, "6,250 clicks at a CPC of 32. What budget do you need?", 200000,
    "6,250 x 32 = 200,000."),
num("A38", MET, "CPA is 1,600 and AOV is 4,800. What is the ROAS?", 3,
    "ROAS = AOV / CPA = 4,800 / 1,600 = 3."),
num("A39", MET, "Impressions 400,000. Reach 100,000. What is the frequency?", 4,
    "400,000 / 100,000 = 4."),
num("A40", MET, "Spend 90,000 at a CPM of 450. How many impressions?", 200000,
    "90,000 / 450 x 1,000 = 200,000."),
num("A41", MET, "Conversions rose from 80 to 104. What is the percentage increase?", 30,
    "24 / 80 = 30%."),
num("A42", MET, "Your target CPA is 900 and your CVR is 3%. What is the maximum CPC you can afford?", 27,
    "Max CPC = target CPA x CVR = 900 x 0.03 = 27."),
mcq("A43", MET, "A campaign's CTR doubled but conversions did not move. The most likely explanation is:",
    ["The tracking broke at the same time",
     "The new ad attracts more clicks but not more qualified intent",
     "Google is throttling the campaign",
     "The budget is too low"], 1,
    "Clickbait improves CTR and destroys CVR. Worth checking tracking, but the copy is the usual culprit."),
mcq("A44", MET, "Which number would you put FIRST in a client report for a lead gen account?",
    ["Impressions", "Click-through rate",
     "Cost per qualified lead against target", "Average position"], 2,
    "Lead with the business outcome. Platform metrics are supporting detail, not the headline."),
mcq("A45", MET, "Your Meta ad set spent 40,000 and reports 20 purchases. Shopify shows 13 from Meta. You should:",
    ["Report the 20 - it is the platform's own data",
     "Report the 13 and explain the attribution difference",
     "Report the average of the two",
     "Stop using Shopify's reporting"], 1,
    "Backend is the source of truth; the platform number is directional. Explaining the gap is part of the job."),
mcq("A46", MET, "A 'conversion' in your Google Ads account is counting both form fills AND phone clicks. This means:",
    ["Nothing - both are leads",
     "Your CPA is a blend of two different actions and may hide a problem in one of them",
     "The account is set up incorrectly and must be rebuilt",
     "Google will automatically separate them"], 1,
    "Blended conversion actions are one of the commonest reasons a CPA looks fine while one channel quietly fails."),
mcq("A47", DIAG, "A campaign's spend dropped to near zero overnight with no changes made. First check:",
    ["Competitor activity",
     "Billing status, ad disapprovals and whether the campaign or ad group is still enabled",
     "The bid strategy target",
     "The landing page speed"], 1,
    "Billing failures and disapprovals cause more sudden stops than any auction dynamic."),
mcq("A48", DIAG, "You inherit an account with no documentation. Your first week should mostly be spent:",
    ["Rebuilding the campaign structure",
     "Auditing structure, tracking, change history and what the client thinks success looks like",
     "Pausing the worst performers",
     "Launching new tests to gather data"], 1,
    "Audit before action. Rebuilding an account you do not yet understand is how good performance gets broken."),
mcq("A49", DIAG, "The client asks for a change you think will hurt performance. You:",
    ["Do it - they are the client",
     "Refuse and explain why",
     "Explain the risk with evidence, propose a test, and do it properly if they still want it",
     "Do it on one campaign only, without telling them"], 2,
    "State the concern, propose a test, then execute properly if overruled. Quiet half-compliance is the worst option."),
mcq("A50", DIAG, "You realise you have been reporting a metric incorrectly for two months. You:",
    ["Correct it going forward and say nothing about the past",
     "Tell your manager immediately with the corrected numbers and the impact",
     "Wait until the quarterly review to raise it",
     "Ask a colleague whether anyone is likely to notice"], 1,
    "Immediate disclosure with the corrected numbers. The delay is what damages trust, not the error."),
mcq("A51", DIAG, "Peak sale weekend and the client's site goes down for three hours. You:",
    ["Leave campaigns running - the traffic will return",
     "Pause or heavily throttle spend, alert the client, then restart gradually",
     "Pause everything permanently and wait for instructions",
     "Increase bids afterwards to make up lost ground"], 1,
    "Contain, communicate, restart gradually. Then quantify the loss and set up an uptime alert."),
mcq("A52", DIAG, "Your manager asks you to do something you are fairly sure is wrong. You:",
    ["Do it as instructed",
     "Ask a question to understand the reasoning, state your concern once with evidence, then commit either way",
     "Do it slowly and hope it gets cancelled",
     "Escalate to their manager"], 1,
    "Understand first, disagree once and clearly, then commit. Passive resistance is the worst of both."),
mcq("A53", DIAG, "A test you designed is showing a clear winner after 3 days. You:",
    ["Roll out the winner immediately",
     "Check whether the sample and the conversion lag justify a conclusion before acting",
     "Stop the test and start a new one",
     "Extend the test indefinitely"], 1,
    "Three days is rarely enough. Check conversions, not clicks, and account for lag before calling it."),
mcq("A54", DIAG, "You are asked to work on an account in a vertical you know nothing about. Day one, you:",
    ["Apply the same structure you use on your other accounts",
     "Learn the customer, the buying cycle and the client's economics before touching settings",
     "Ask to be reassigned",
     "Copy a competitor's setup"], 1,
    "Understand the business before the account. Template-applying is how accounts get structurally wrong from day one."),
]

ASSOC_WRITTEN_EXTRA = [
wr("AW5", "Walk us through how you would audit a Google Ads account you have just been given access to. "
   "What do you look at, in what order, and why that order?", 200,
   "Look for tracking validity first, then structure, then performance - not the reverse. A candidate who starts "
   "with keyword bids has not learned that most account problems are measurement or structure problems."),
wr("AW6", "Tell us about a time you disagreed with how something was being done and said so. What happened?", 150,
   "Tests whether they will speak up at all, and how. Strong answers show they understood the other side first, "
   "raised it once with reasoning, and committed to the outcome. 'I just did what I was told' is a 0-1."),
wr("AW7", "Pick one metric you check every single day on the accounts you run, and one you deliberately ignore "
   "day to day. Explain both choices.", 150,
   "The 'deliberately ignore' half is the real question - it tests whether they understand noise, conversion lag "
   "and which numbers are diagnostics rather than decisions. Someone who checks everything daily is reacting, not managing."),
]
