# -*- coding: utf-8 -*-
"""Auto-scored assessment bank. 'a' and 'why' are stripped from the candidate build."""

FUND = "Platform fundamentals"
MET  = "Metrics & numeracy"
DIAG = "Diagnostic judgment"

def mcq(id, sec, q, opts, a, why, track="both"):
    return {"id": id, "sec": sec, "type": "mcq", "q": q, "opts": opts, "a": a, "why": why, "track": track}

def num(id, sec, q, a, why, tol=0.02, track="both", hint=""):
    return {"id": id, "sec": sec, "type": "num", "q": q, "a": a, "why": why, "tol": tol,
            "track": track, "hint": hint}

def wr(id, q, words, guide, track="both"):
    return {"id": id, "type": "text", "q": q, "words": words, "guide": guide, "track": track}


# =========================================================================== INTERN
INTERN_AUTO = [
mcq("I01", FUND, "In Google Ads, at which level is the daily budget set?",
    ["Account", "Campaign", "Ad group", "Keyword"], 1,
    "Budget, bid strategy, location, schedule and network are all campaign-level settings."),
mcq("I02", FUND, "In Meta Ads, which of these is decided at the AD SET level?",
    ["The creative and the headline", "The campaign objective",
     "The audience and the optimisation event", "The payment method"], 2,
    "Campaign = objective. Ad set = audience, placements, optimisation event, schedule. Ad = creative."),
mcq("I03", FUND, "A user types 'best running shoes for flat feet' into Google. In Google Ads this is called:",
    ["A keyword", "A search term", "An ad group theme", "A quality signal"], 1,
    "A keyword is what you bid on. A search term is what the user actually typed. They are frequently different."),
mcq("I04", FUND, "Which campaign type CAPTURES existing demand rather than creating it?",
    ["YouTube in-stream video", "Display", "Search", "Demand Gen"], 2,
    "Search captures people already looking. Display, Video and Demand Gen interrupt people who were not."),
mcq("I05", FUND, "Quality Score is made up of:",
    ["Budget, bid and impressions",
     "Expected CTR, ad relevance and landing page experience",
     "CTR, conversion rate and ROAS",
     "Account age, spend level and click volume"], 1,
    "Three components. None of them is how much you spend - a common misconception."),
mcq("I06", FUND, "What does a negative keyword do?",
    ["Lowers your bid for that keyword",
     "Stops your ad showing for search terms containing that word",
     "Removes the keyword from your ad group",
     "Tells Google the keyword performed badly"], 1,
    "It is an exclusion, not a bid modifier."),
mcq("I07", FUND, "Which statement about EXACT match is true?",
    ["Your ad only shows for the exact words typed, in that exact order",
     "It can still match close variants such as plurals, misspellings and same-meaning phrasing",
     "It is only available on Shopping campaigns",
     "It always costs more per click than phrase match"], 1,
    "Exact match has not been literal for years. Close variants are why the search terms report still matters."),
mcq("I08", FUND, "On Meta, the campaign objective primarily determines:",
    ["The maximum budget you are allowed to set",
     "Who Meta shows the ad to and what outcome it optimises for",
     "Which placements are available",
     "How much you are charged per click"], 1,
    "The objective picks the optimisation model. Choosing Traffic to get cheap clicks is the classic error."),
num("I09", MET, "Spend 40,000. Clicks 800. What is the CPC?", 50,
    "CPC = cost / clicks = 40,000 / 800 = 50."),
num("I10", MET, "Clicks 1,000. Impressions 25,000. What is the CTR, as a percentage? (enter the number only)", 4,
    "CTR = clicks / impressions = 1,000 / 25,000 = 4%."),
num("I11", MET, "Spend 60,000. Conversions 30. What is the CPA?", 2000,
    "CPA = cost / conversions = 60,000 / 30 = 2,000."),
num("I12", MET, "Spend 25,000. Revenue 100,000. What is the ROAS? (enter as a number, e.g. 3.5)", 4,
    "ROAS = revenue / cost = 100,000 / 25,000 = 4."),
num("I13", MET, "Clicks 500. Conversions 20. What is the conversion rate, as a percentage?", 4,
    "CVR = conversions / clicks = 20 / 500 = 4%."),
num("I14", MET, "Spend 30,000. Impressions 20,000. What is the CPM?", 1500,
    "CPM = cost / impressions x 1,000 = 30,000 / 20,000 x 1,000 = 1,500. Forgetting the x1,000 is the usual slip."),
mcq("I15", MET, "CPA has risen over the last month, but CPC has not changed. The most likely explanation is:",
    ["Competitors are bidding more aggressively",
     "The conversion rate has fallen",
     "Your budget is too low",
     "Impressions have dropped"], 1,
    "CPA = CPC / CVR. If CPC is flat and CPA rose, CVR must have fallen - so the problem is after the click."),
mcq("I16", MET, "Campaign A: 3 conversions, ROAS 9.0. Campaign B: 180 conversions, ROAS 3.2. What should you do?",
    ["Move most of the budget into Campaign A immediately",
     "Pause Campaign B",
     "Treat Campaign A's ROAS as unreliable - 3 conversions is too small a sample to act on",
     "Split the budget evenly between them"], 2,
    "Sample size before decision. Three conversions is noise, not evidence."),
mcq("I17", DIAG, "Conversions dropped to zero overnight with no change in spend or clicks. What do you check FIRST?",
    ["Whether competitors have entered the auction",
     "Whether the conversion tracking is still firing",
     "Whether you should raise bids",
     "Whether the season has changed"], 1,
    "Zero conversions with normal traffic is a tracking failure until proven otherwise. Always rule out measurement first."),
mcq("I18", DIAG, "You are given a task, the instructions are unclear, and your manager is in back-to-back meetings. Best action:",
    ["Wait until they are free so you do not get it wrong",
     "Guess and complete it so it is done on time",
     "Attempt it, note your specific questions and assumptions, and send one consolidated message",
     "Ask a different colleague to do it for you"], 2,
    "Attempt, document assumptions, ask once and precisely. This is the single most testable work-habit signal at intern level."),
]

INTERN_WRITTEN = [
wr("IW1", "Tell us about something in marketing you taught yourself in the last three months, without anyone asking you to. "
   "What did you learn, where did you learn it, and what did you actually do with it?", 150,
   "Specific, recent and verifiable, with a real application. The application is the point - consuming content is not learning. "
   "Score 3 if they name the source and what they did with it. Score 0-1 for 'I watch a lot of YouTube'."),
wr("IW2", "Pick a product or app you use every day. Who is the customer, what would you write as a Google search ad headline "
   "(30 characters maximum), and what is the first thing you would test?", 150,
   "Thinks about the customer before the ad. Headline is specific rather than a generic superlative, and within 30 characters. "
   "Names ONE testable variable and what result would tell them something. Structure of thinking beats polish."),
]

# ======================================================================== ASSOCIATE
ASSOC_AUTO = [
mcq("A01", FUND, "Shared negative keyword lists are best used for:",
    ["Every negative you ever find, to keep things in one place",
     "Account-wide irrelevant themes applied across many campaigns",
     "Negatives that only apply to a single ad group",
     "Competitor brand names only"], 1,
    "Shared lists for account-wide junk. Campaign level for intent tiering. Ad group level for cross-negation."),
mcq("A02", FUND, "Which bid strategy would you avoid on an account generating 3 conversions per month?",
    ["Maximise Clicks", "Manual CPC", "Target ROAS", "Target Impression Share"], 2,
    "Value-based automated bidding needs conversion volume. With 3 conversions a month it has nothing to learn from."),
mcq("A03", FUND, "Ad Rank is determined by:",
    ["Your maximum bid alone",
     "Bid, ad quality, Ad Rank thresholds, auction context and expected impact of assets",
     "Quality Score multiplied by daily budget",
     "Click-through rate and account spend history"], 1,
    "Relevance lowers your actual CPC, not just your position. 'Highest bid wins' is the classic wrong answer."),
mcq("A04", FUND, "Search Lost IS (budget) of 45% means:",
    ["45% of your clicks were wasted",
     "You lost 45% of available impressions because the campaign was limited by budget",
     "Your budget is 45% higher than it needs to be",
     "45% of competitors outranked you"], 1,
    "Distinguishing lost IS (budget) from lost IS (rank) tells you whether the constraint is money or quality."),
mcq("A05", FUND, "A responsive search ad allows a maximum of:",
    ["10 headlines and 2 descriptions", "15 headlines and 4 descriptions",
     "5 headlines and 5 descriptions", "20 headlines and 4 descriptions"], 1,
    "15 and 4. Worth knowing because the practical skill is writing 15 genuinely distinct angles, not 15 rewordings."),
mcq("A06", FUND, "Pinning a headline to position 1:",
    ["Guarantees a higher Quality Score",
     "Reduces the number of ad combinations Google can test",
     "Has no effect on delivery",
     "Is required for all brand campaigns"], 1,
    "Pinning trades testing surface for control. Use it for legal or brand requirements, not as a default habit."),
mcq("A07", FUND, "A campaign with a 5,000 daily budget spent 6,200 yesterday. This is:",
    ["An error you should report to the client immediately",
     "Normal - Google can overdeliver on a given day but caps at the monthly charging limit",
     "A sign the bid strategy is broken",
     "Only possible if someone changed the budget"], 1,
    "Average daily budget x 30.4 is the monthly cap. Daily overspend is expected and self-corrects."),
mcq("A08", FUND, "You need to make 300 changes across an account. The safest approach is:",
    ["Make them in the UI one at a time so you can check each one",
     "Export a backup, make the changes in Google Ads Editor, run the error check, post, then verify in change history",
     "Use a script so it happens instantly",
     "Ask the client to approve each change first"], 1,
    "The backup and the post-change verification are the parts people skip, and they are the parts that matter."),
mcq("A09", FUND, "Meta's learning phase typically exits after approximately:",
    ["50 optimisation events per ad set per week",
     "1,000 impressions per ad",
     "7 days regardless of volume",
     "100 clicks per ad set"], 0,
    "~50 events per ad set per week. This is why splitting a small budget across many ad sets fails."),
mcq("A10", FUND, "Which of these resets the Meta learning phase?",
    ["Adding a new comment reply",
     "A significant edit to the ad set's budget, audience or optimisation event",
     "Any change to the campaign name",
     "Viewing the ad set in Ads Manager"], 1,
    "Meaningful edits reset learning. Daily tinkering is why some accounts never stabilise."),
mcq("A11", FUND, "The Conversions API is used to:",
    ["Replace the pixel entirely",
     "Send events server-side alongside the pixel, deduplicated using a shared event ID",
     "Import Google Ads conversions into Meta",
     "Automatically create lookalike audiences"], 1,
    "Alongside, not instead of. The shared event_id is what prevents double counting."),
mcq("A12", FUND, "Event Match Quality measures:",
    ["How relevant your creative is to the audience",
     "How well the customer information you send matches Meta users",
     "How many conversions an ad set produced",
     "The quality score of your landing page"], 1,
    "Low EMQ means Meta cannot attribute or optimise properly. Fixed by passing more hashed parameters."),
mcq("A13", FUND, "Advantage+ placements are generally recommended because:",
    ["They only show ads on Facebook and Instagram feeds",
     "They let Meta find cheaper inventory across all available placements",
     "They exclude Audience Network by default",
     "They guarantee a lower CPA"], 1,
    "Restricting placements restricts the auction. Exclude only with placement-level evidence, not on reputation."),
mcq("A14", FUND, "A lookalike audience is best built from:",
    ["The largest customer list you can find",
     "All website visitors from the last 180 days",
     "Your highest-value customers, even if that list is relatively small",
     "People who engaged with any post"], 2,
    "Seed quality beats seed size. A lookalike of all leads inherits the quality of all leads, including the bad ones."),
num("A15", MET, "Spend 250,000. Conversions 200. Revenue 900,000. What is the ROAS?", 3.6,
    "900,000 / 250,000 = 3.6."),
num("A16", MET, "CPC is 40 and conversion rate is 2.5%. What is the CPA?", 1600,
    "CPA = CPC / CVR = 40 / 0.025 = 1,600."),
num("A17", MET, "You need 100 leads at a target CPL of 800. What budget do you need?", 80000,
    "100 x 800 = 80,000."),
num("A18", MET, "CPM is 300 and CTR is 1.5%. What is the CPC?", 20,
    "CPC = CPM / (1,000 x CTR) = 300 / (1,000 x 0.015) = 20."),
mcq("A19", MET, "GA4 consistently reports fewer conversions than Google Ads. The most likely reason is:",
    ["Google Ads is inflating the numbers deliberately",
     "They use different attribution models and different date logic",
     "The GA4 tag is broken",
     "Someone applied a filter in GA4"], 1,
    "Ads reports on click date with data-driven attribution; GA4 is session-based, last-non-direct-click. They should not match."),
mcq("A20", MET, "Why should you not make decisions on yesterday's performance today?",
    ["The data refreshes only once a week",
     "Conversion lag - conversions are reported back to the click date, so recent days always understate",
     "Google randomises recent data to prevent manipulation",
     "Yesterday's data is always inaccurate"], 1,
    "Exclude the last 3-7 days depending on the account's measured lag, and agree that convention with the client."),
mcq("A21", DIAG, "CPL has risen 60% over eight weeks. Which do you check FIRST?",
    ["Competitor ad copy",
     "Change history and conversion tracking",
     "Whether to increase bids",
     "The client's landing page design"], 1,
    "Check what changed and whether measurement is intact before forming any theory. Almost every wasted week starts by skipping this."),
mcq("A22", DIAG, "A search term has spent 40,000 across three months with zero conversions. You should:",
    ["Add it as a negative immediately",
     "Increase the bid to give it a fair chance",
     "Check whether the intent is genuinely irrelevant, then negative it if so",
     "Ignore it - three months is too short to judge"], 2,
    "Usually a negative, but not automatically: a high-intent term with a broken landing page needs a different fix."),
mcq("A23", DIAG, "A test is trending negative on day 4 of a planned 14-day run. You should:",
    ["Stop it immediately to limit the damage",
     "Let it run unless it is causing real harm - day 4 is noise",
     "Double the budget to reach significance faster",
     "Change one variable and continue"], 1,
    "Stopping early is how you learn nothing. Have a pre-agreed harm threshold, and hold the line otherwise."),
mcq("A24", DIAG, "The client wants a report at 5pm. At 4:45 you spot an error in the data. You:",
    ["Send it on time and correct it tomorrow",
     "Send it with the error, since the trend is still roughly right",
     "Tell them it will be 30 minutes late and why",
     "Remove the affected section without mentioning it"], 2,
    "Late and correct beats on-time and wrong. How someone handles this predicts how they handle a real mistake."),
]

ASSOC_WRITTEN = [
wr("AW1", "Describe a specific change you personally made in a Google Ads or Meta account that improved performance. "
   "State what the account was, what the numbers were before and after, over what period, and exactly what you changed.", 200,
   "Look for settings-level specificity and a stated baseline and timeframe. Someone who did the work names the mechanism; "
   "someone who watched it happen stays general. Score 0-1 if no numbers or no timeframe."),
wr("AW2", "Tell us about a mistake you made that cost a client money or time. What did you do in the first hour?", 150,
   "Speed of disclosure is the signal, not the size of the mistake. Score 3 for immediate disclosure plus a control put in place. "
   "Score 0 for 'I have not made one' or for a mistake that turns out to be someone else's fault."),
wr("AW3", "A client says 60% of the leads you are generating are junk. List the first five things you would check, "
   "in order, and explain why that order.", 200,
   "Should define 'junk' with the client first, then work source-outward: search terms, form friction, geo, "
   "creative promise, then the client's own follow-up speed. Order and reasoning matter more than the list.", "lg"),
wr("AW4", "A client's Shopping ROAS is 4.0, but the founder says the business is losing money on marketing. "
   "Give three possible explanations.", 200,
   "Strong answers include: margin too thin for a 4.0 ROAS, platform ROAS double-counting or overlapping with Meta, "
   "heavy retargeting harvesting existing demand, returns and discounting not accounted for, brand traffic inflating the number.", "ec"),
]

# ========================================================================== MANAGER
MGR_AUTO = [
mcq("M01", FUND, "Offline conversion import requires you to capture and store:",
    ["The user's email address only",
     "The GCLID against the lead record in the CRM",
     "The campaign name in a hidden form field",
     "The IP address of the visitor"], 1,
    "GCLID (or WBRAID/GBRAID) captured on the form and stored against the lead. Without it there is nothing to upload against."),
mcq("M02", FUND, "Enhanced Conversions for Leads is most useful when:",
    ["You want to increase your conversion volume artificially",
     "You cannot reliably capture the GCLID and need to match on hashed email or phone instead",
     "You are running Display campaigns",
     "The client refuses to install any tracking"], 1,
    "It is the fallback when GCLID capture is not feasible, not a replacement for a proper OCI setup."),
mcq("M03", FUND, "Under data-driven attribution, a conversion is reported on:",
    ["The date the conversion happened",
     "The date of the click that led to it",
     "The date the campaign started",
     "The date of the last impression"], 1,
    "Click date, which is why recent days back-fill and should never be judged as final."),
mcq("M04", FUND, "The biggest risk of running Performance Max on a lead gen account is:",
    ["It always costs more per click",
     "Lead quality dilution, with limited query-level control",
     "It cannot run alongside Search campaigns",
     "It requires a product feed"], 1,
    "Only sensible with lead scoring and OCI feeding back, plus brand exclusions and campaign-level negatives."),
mcq("M05", FUND, "Brand exclusions in Performance Max are used to:",
    ["Stop competitors bidding on your brand",
     "Prevent PMax absorbing brand traffic that should sit in a controlled search campaign",
     "Remove your brand from Display placements",
     "Exclude branded products from the feed"], 1,
    "Without them, PMax claims cheap brand conversions and the headline ROAS flatters the campaign."),
mcq("M06", FUND, "Custom labels in a product feed exist to:",
    ["Improve the product's search ranking",
     "Segment products by business logic such as margin, price band, bestseller or seasonality",
     "Replace the product_type attribute",
     "Add promotional text to the listing"], 1,
    "They are how you make bidding follow profit rather than revenue."),
mcq("M07", FUND, "A Merchant Center 'misrepresentation' disapproval usually relates to:",
    ["Image resolution being too low",
     "A mismatch between the site and the feed, or missing trust and policy information on the site",
     "The product price being too high",
     "Too many products in the feed"], 1,
    "Usually returns/contact/policy pages, unclear pricing or feed-to-site mismatch - not a feed formatting issue."),
mcq("M08", FUND, "Before moving an account from tCPA to tROAS, the most important prerequisite is:",
    ["A larger daily budget",
     "Verified, correctly passed conversion values",
     "At least 12 months of account history",
     "Switching all campaigns to broad match"], 1,
    "tROAS optimises to the value you send it. Wrong values means confidently optimising to the wrong thing."),
mcq("M09", FUND, "An initial tROAS target should be set based on:",
    ["The client's desired ROAS",
     "The account's trailing achieved ROAS",
     "The industry benchmark",
     "Double the current ROAS, to create headroom"], 1,
    "Set from what the account actually achieves, then step 10-15% at a time allowing relearning between moves."),
mcq("M10", FUND, "Advantage+ Shopping's headline ROAS tends to overstate incremental performance because:",
    ["Meta uses a different currency conversion",
     "It absorbs retargeting and existing demand within a single reported number",
     "It counts impressions as conversions",
     "It excludes new customers by default"], 1,
    "Which is why the existing-customer budget cap and new-customer share are the metrics that matter."),
mcq("M11", FUND, "Meta's default attribution setting is:",
    ["1-day click only", "7-day click and 1-day view",
     "28-day click and 28-day view", "Last click across all channels"], 1,
    "7-day click / 1-day view. Comparing it to a last-click backend is comparing two different questions."),
mcq("M12", FUND, "The correct way to run a split test on Meta is:",
    ["Duplicate the ad set and change one variable",
     "Use the A/B test tool, which splits users rather than ad sets",
     "Run the variants in different weeks and compare",
     "Run both in the same ad set and compare ad-level data"], 1,
    "Duplicating creates auction overlap and unequal delivery, so the result is not attributable to the variable."),
mcq("M13", FUND, "Under Consent Mode v2, some conversions are modelled. This means:",
    ["They are estimates that cannot be matched to individual users",
     "They are duplicates and should be removed",
     "They only appear in GA4",
     "They are conversions from users who blocked ads"], 0,
    "So platform and CRM will never reconcile exactly. Set that expectation before it becomes an argument."),
mcq("M14", FUND, "An ad account gets restricted. The one thing you should NOT do is:",
    ["Read the specific policy cited",
     "Audit the landing page for the violation",
     "Create a replacement ad account or Business Manager",
     "Submit a request for review"], 2,
    "Spinning up a new asset risks the entire Business Manager being flagged."),
num("M15", MET, "AOV is 2,500. COGS is 1,000. Shipping and payment fees are 300. "
    "What is the contribution margin, as a percentage?", 48,
    "(2,500 - 1,300) / 2,500 = 48%."),
num("M16", MET, "Contribution margin is 40%. What is the break-even ROAS?", 2.5,
    "Break-even ROAS = 1 / contribution margin = 1 / 0.40 = 2.5."),
num("M17", MET, "A client wants 40 sales a month. Close rate is 25% and lead-to-SQL is 40%. "
    "How many leads are needed per month?", 400,
    "40 / 0.25 = 160 SQLs. 160 / 0.40 = 400 leads."),
num("M18", MET, "Same client: target CAC is 12,000 and 400 leads are needed. What CPL do you need?", 1200,
    "Budget = 40 x 12,000 = 480,000. CPL = 480,000 / 400 = 1,200."),
num("M19", MET, "Backend revenue is 8,000,000 and total ad spend across all channels is 2,500,000. What is the MER?", 3.2,
    "MER = total revenue / total ad spend = 3.2. Platform-agnostic, so immune to cross-channel double counting."),
mcq("M20", MET, "Campaign A is at 3.0 ROAS, Campaign B is at 5.0 ROAS. Should you move the whole budget to B?",
    ["Yes - B is clearly more efficient",
     "No - average ROAS says nothing about what the next rupee into B would return",
     "Yes, but only 50% of it",
     "No - you should never move budget between campaigns"], 1,
    "B may be saturated or audience-limited. Check headroom, move incrementally, measure marginal return."),
mcq("M21", MET, "Google and Meta together report more revenue than the client's backend shows. This indicates:",
    ["The backend is under-reporting",
     "Double counting and overlapping attribution between the platforms",
     "A currency error",
     "Fraud in one of the accounts"], 1,
    "Both platforms claim the same conversion. It is why MER exists as a governing metric."),
mcq("M22", MET, "The strongest available evidence that your ads caused sales is:",
    ["A high platform-reported ROAS",
     "A geo holdout or conversion lift test",
     "A rising conversion rate",
     "Positive client feedback"], 1,
    "Everything in a dashboard is correlation. Only a holdout gives you causation."),
mcq("M23", DIAG, "CPL is up 45%, volume is flat, and lead-to-SQL has fallen from 32% to 19%. "
    "The most likely driver is:",
    ["Bids are set too low",
     "A change in traffic quality or source mix",
     "Seasonality",
     "The landing page has slowed down"], 1,
    "A simultaneous CPL rise and SQL-rate fall points at what kind of traffic you are buying, not at bid levels."),
mcq("M24", DIAG, "Your associate made a bulk edit that broke pacing across four campaigns. Your first action is:",
    ["Escalate it to HR",
     "Contain the damage, then speak to them directly and privately",
     "Fix it yourself and say nothing to avoid discouraging them",
     "Raise it in the next team meeting as a learning example"], 1,
    "Contain first, then a direct private conversation. Silence teaches nothing; public correction teaches fear."),
mcq("M25", DIAG, "A client demands a 50% CPL reduction in 30 days and you believe it is not achievable. You should:",
    ["Agree, and manage expectations later",
     "Refuse and explain that the request is unrealistic",
     "State the constraint with evidence, offer the achievable trade-off, and confirm it in writing",
     "Agree to try, without committing to the number"], 2,
    "Name the constraint, offer the real trade-off (lower CPL at lower volume), and document what was agreed."),
mcq("M26", DIAG, "You are asked to present the numbers in a way that flatters performance. You:",
    ["Do it - the client relationship comes first",
     "Decline, and offer a fair comparison period and honest framing instead",
     "Do it once and raise it internally afterwards",
     "Present both versions and let the client choose"], 1,
    "Credibility is the asset. Flattered numbers create a bigger problem the following month."),
]

MGR_WRITTEN = [
wr("MW1", "A client's blended MER has fallen from 3.2 to 2.4 over a quarter while platform-reported ROAS held steady "
   "at around 4.0. Revenue is up 8%; spend is up 44%. Explain to the founder, in plain language, what is most likely "
   "happening and what you would do about it.", 250,
   "Should reach marginal versus average return: the extra 44% of spend bought far less than the first rupee did. "
   "Bonus for spotting attribution inflation and retargeting harvesting existing demand. Must be readable by a non-marketer. "
   "Score 0-1 if they conclude performance is fine because ROAS held."),
wr("MW2", "Describe an account you own or have owned. What was the client's target, what did you change last quarter, "
   "and what is the one thing you have not been able to fix?", 250,
   "The unfixed thing is the real question - it tests honesty and self-awareness. Look for a specific target with a reason "
   "behind it, and a change described at settings level. Score 0-1 if everything they touched worked."),
wr("MW3", "Describe the last time you were accountable for missing a target. What did you tell the client, and when?", 200,
   "Timing is the signal: did the client hear it from them early, or find out themselves? Look for a revised forecast and a "
   "specific ask, not reassurance. Deflection onto the market, the season or the client is a 0."),
]

# ===================================================================== SR. MANAGER
SR_AUTO = [
num("S01", MET, "Contribution margin is 35%. What is the break-even ROAS? (two decimal places)", 2.86,
    "1 / 0.35 = 2.857, so 2.86.", 0.02),
num("S02", MET, "Monthly fee revenue is 3,000,000. Your largest client is 40% of that. Servicing that client costs "
    "60% of its fee. If it churns, how much monthly gross profit do you lose?", 480000,
    "Fee = 1,200,000. Cost = 720,000. Gross profit lost = 480,000."),
num("S03", MET, "Spend rises from 2,000,000 to 2,800,000. Revenue rises from 7,000,000 to 8,400,000. "
    "What is the marginal ROAS on the additional spend?", 1.75,
    "(8,400,000 - 7,000,000) / (2,800,000 - 2,000,000) = 1,400,000 / 800,000 = 1.75."),
mcq("S04", MET, "In the scenario above, average ROAS fell from 3.5 to 3.0 and break-even ROAS is 2.5. "
    "What does that tell you?",
    ["Performance is still acceptable - the average is above break-even",
     "The incremental spend is losing money, even though the average still looks healthy",
     "The spend increase was too small to judge",
     "Break-even ROAS is the wrong metric here"], 1,
    "Marginal ROAS of 1.75 against a 2.5 break-even means the additional 800,000 destroyed value. "
    "The average hides it. This is the single most expensive mistake in scaling accounts."),
num("S05", MET, "Target payback period is 3 months. A customer generates 800 of contribution per month. "
    "What is the maximum CAC you can justify?", 2400,
    "3 x 800 = 2,400."),
mcq("S06", MET, "First-order contribution is 900 and CAC is 1,500. The first order is:",
    ["Profitable", "Loss-making, and only justified if repeat purchase covers the gap within an agreed payback window",
     "Break-even", "Impossible to assess without knowing ROAS"], 1,
    "Buying first orders at a loss is a legitimate strategy - but only with cohort data and the client's finance side agreeing the window."),
mcq("S07", MET, "The most reliable input when forecasting the effect of a budget increase is:",
    ["Last month's average CPA",
     "The historical marginal CPA/ROAS curve plus remaining impression share",
     "The client's growth target",
     "Industry benchmark growth rates"], 1,
    "Average performance tells you nothing about what the next unit of spend returns."),
mcq("S08", MET, "A client already holds 85% impression share on non-brand search and asks to double spend. "
    "The most likely outcome is:",
    ["A proportional increase in conversions",
     "Sharply diminishing returns on search - growth has to come from other channels, audiences or geographies",
     "A large drop in CPC due to increased volume",
     "Improved Quality Score from higher spend"], 1,
    "There is almost no headroom left. Promising linear scaling here is how accounts and relationships break."),
mcq("S09", DIAG, "A client representing 40% of portfolio revenue is significantly over-serviced. Your first move is:",
    ["Hire an additional associate to cover the workload",
     "Reduce the service level and inform the client",
     "Audit where the hours actually go, then redesign scope or renegotiate the fee",
     "Absorb the cost - the account is too important to risk"], 2,
    "Understand the hours before you change headcount, service level or price. Usually the hours are in reporting and ad-hoc requests."),
mcq("S10", DIAG, "Two accounts are at renewal risk within 90 days. Your first action is:",
    ["Improve performance as quickly as possible",
     "Diagnose the actual cause of dissatisfaction, which is often communication rather than performance",
     "Offer a fee reduction to retain them",
     "Assign your strongest manager to both"], 1,
    "Churn is frequently about feeling unheard or uninformed. Fixing performance without fixing that loses the account anyway."),
mcq("S11", DIAG, "An associate is consistently underutilised. The right response is:",
    ["Give them more shadowing time",
     "Redistribute work and give them owned scope with a review layer",
     "Wait until the portfolio grows",
     "Move them to a different team"], 1,
    "Underutilisation is a delegation failure, not a capability failure. Owned scope with review is how people grow."),
mcq("S12", DIAG, "A manager is technically strong but defensive with clients. You should:",
    ["Remove them from all client contact",
     "Coach on the specific behaviour with observed calls, clear expectations and a timeline",
     "Accept it, because the technical work is what matters",
     "Pair them permanently with someone who handles the calls"], 1,
    "Coach the behaviour with evidence, not the personality. Be willing to move them if it does not change."),
mcq("S13", DIAG, "Deciding the Google/Meta split for a new client should start from:",
    ["An industry-standard split such as 60/40",
     "Category search volume and intent, versus the need to create demand",
     "Whichever platform the client already uses",
     "Whichever platform your team is stronger on"], 1,
    "Google captures existing demand; Meta creates it. The split is a hypothesis with a stated reallocation rule, not a formula."),
mcq("S14", DIAG, "Incrementality testing matters most on:",
    ["New prospecting campaigns",
     "Brand and retargeting campaigns",
     "Display campaigns",
     "Any campaign under 10% of budget"], 1,
    "Brand and retargeting take the most credit for demand that already existed. That is where the overstatement lives."),
mcq("S15", DIAG, "The right governing metric for an ecommerce portfolio is:",
    ["Summed platform ROAS across channels",
     "Backend MER and new-customer CAC",
     "Average CPC across accounts",
     "Total conversions reported by each platform"], 1,
    "Summed platform ROAS double counts by design. MER and new-customer CAC are what the client's P&L actually feels."),
mcq("S16", DIAG, "You should agree the source of truth for reporting with a client:",
    ["After the first month, once you understand the data",
     "Before the first reporting cycle",
     "Only if a discrepancy arises",
     "At the quarterly review"], 1,
    "Agreeing it after a discrepancy appears looks like moving the goalposts, however correct you are."),
mcq("S17", DIAG, "The main reason to run a brand holdout test is:",
    ["To reduce spend on brand terms",
     "To measure how much brand-search conversion volume is genuinely incremental to organic",
     "To improve Quality Score on brand keywords",
     "To stop competitors bidding on your brand"], 1,
    "It answers the one brand question clients actually ask, with evidence instead of assertion."),
mcq("S18", DIAG, "A process you build is genuinely valuable when:",
    ["It is documented in detail",
     "It is still used after you stop enforcing it",
     "It saves at least an hour per week",
     "Every team member has been trained on it"], 1,
    "Survival without enforcement is the only real test. Everything else is a document nobody opens."),
mcq("S19", DIAG, "A hire that does not work out is most often explained by:",
    ["Bad luck",
     "A signal the interviewer noticed but did not probe",
     "Poor onboarding",
     "The candidate misrepresenting themselves"], 1,
    "Almost always there was a moment of doubt that nobody chased. That is what the must-pass gate is for."),
mcq("S20", DIAG, "Scope creep is best managed by:",
    ["Referring to the contract when it becomes significant",
     "Naming the pattern early and making the trade-off visible",
     "Absorbing it to protect the relationship",
     "Charging for every additional request"], 1,
    "Say yes to small things, name the pattern early on large ones, and make the trade-off visible rather than silent."),
mcq("S21", DIAG, "Reducing servicing hours by 20% should start with:",
    ["Cutting optimisation time",
     "Auditing where the hours actually go - usually reporting and ad-hoc requests",
     "Reducing meeting frequency with clients",
     "Moving accounts to junior staff"], 1,
    "Cutting optimisation time is cutting the product. The hours are almost always elsewhere."),
mcq("S22", DIAG, "In a pitch, when you do not know the answer to a technical question you should:",
    ["Give your best guess confidently",
     "Say you do not know, say how you would find out, and commit to a specific follow-up time",
     "Redirect to a topic you know well",
     "Defer to a colleague and move on"], 1,
    "A senior person who cannot say 'I do not know' is a liability in front of clients. Then actually follow up."),
mcq("S23", DIAG, "An underperforming team member who is well-liked should be:",
    ["Given more time, since morale matters",
     "Given explicit expectations, a timeline and support - and managed out if it does not change",
     "Moved quietly to another team",
     "Given a smaller portfolio indefinitely"], 1,
    "Tolerating it is a decision that costs the rest of the team. Clarity and a timeline is the kind version."),
mcq("S24", DIAG, "The first two weeks of taking over a new portfolio should be spent:",
    ["Restructuring the weakest accounts",
     "Diagnosing - accounts, clients, team and commercials - before changing anything material",
     "Meeting every client to reassure them",
     "Building a new reporting template"], 1,
    "Diagnose before you act. Being able to name what you will deliberately NOT do is the senior signal."),
]

SR_WRITTEN = [
wr("SW1", "You have just taken over a portfolio of six accounts totalling 9,000,000 a month in spend, with a team of four "
   "(one manager, two associates, one intern). Two accounts are at renewal risk within 90 days, and the largest account is "
   "40% of portfolio revenue and over-serviced. Outline your first 30 days - and explicitly state what you will NOT do.", 300,
   "The 'will not do' is the whole question. Look for prioritisation by revenue at risk, diagnosis before action, "
   "and a refusal to promise everything. Score 0-1 for a generic 30/60/90 template that ignores the specifics given."),
wr("SW2", "The largest client wants to double spend over two quarters. What would need to be true for that to work, "
   "and how would you forecast it?", 300,
   "Should name conditions: impression share headroom, audience saturation, creative production capacity, landing page and "
   "offer capacity, fulfilment. Forecast built on marginal returns with a range and stated assumptions, plus a staged ramp "
   "with review gates. Score 0-1 for any answer implying linear scaling."),
wr("SW3", "Describe a process you built that is still in use after you stopped enforcing it. What was it, and why did it survive?", 200,
   "Tests whether they build capability or just output. The 'why it survived' answer usually reveals whether they understand "
   "adoption - it survived because it saved the user time, not because it was mandated."),
]

LEVELS = {
    "intern":    {"label": "Intern",       "minutes": 25, "auto": INTERN_AUTO, "written": INTERN_WRITTEN},
    "associate": {"label": "Associate",    "minutes": 35, "auto": ASSOC_AUTO,  "written": ASSOC_WRITTEN},
    "manager":   {"label": "Manager",      "minutes": 40, "auto": MGR_AUTO,    "written": MGR_WRITTEN},
    "senior":    {"label": "Sr. Manager",  "minutes": 45, "auto": SR_AUTO,     "written": SR_WRITTEN},
}

# Weakness -> what to probe in the final interview (maps to the workbook question IDs)
PROBE_MAP = {
    FUND: "Platform craft is the gap. Probe with GA-03, GA-09, GA-20 and MT-08, MT-13 from the workbook - "
          "ask them to walk through a real account they ran, at settings level.",
    MET:  "Measurement and numeracy is the gap. This is the hardest thing to train. Probe with MX-03, MX-05, MX-07 "
          "and re-run a live calculation out loud in the interview before proceeding.",
    DIAG: "Judgment is the gap. Probe with SI-01, SI-03, SI-09 and the level-appropriate case study. "
          "Watch whether they diagnose or react.",
    "written": "Written answers are the gap - usually ownership, honesty or communication. Probe with OA-04, OA-06, "
               "OA-13 and press for a specific example on every claim.",
}
